basketball_site/basketball_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('players.urls')),
]

basketball_site/players/urls.py
from django.urls import path

from .views import PlayerListView, PlayerDetailView, PlayerCreateView, PlayerDeleteView, PlayerUpdateView

urlpatterns = [
  path('players/<int:pk>/', PlayerDetailView.as_view(), name='players'),
  path('', PlayerListView.as_view(), name='home'),
  path('players/new/', PlayerCreateView.as_view(), name='player_new'),
  path('players/delete/<int:pk>', PlayerDeleteView.as_view(), name='player_delete'),
  path('players/<int:pk>/edit/', PlayerUpdateView.as_view(), name='player_edit'),

]

basketball_site/players/models.py
from django.db import models
from django.urls import reverse
positions = (
  ('1', 'PG'),
  ('2', 'SG'),
  ('3', 'SF'),
  ('4', 'PF'),
  ('5', 'C'),
)
# Create your models here.
class Player(models.Model):
   player_name = models.CharField(max_length=50)
   author = models.ForeignKey('auth.User', on_delete=models.CASCADE,)
   height = models.DecimalField(max_digits=4, decimal_places=2)
   weight = models.DecimalField(max_digits=5, decimal_places=2)
   position = models.CharField(max_length=20, choices=positions, default='water boy')

   def __str__(self):
     return self.player_name
    
   def get_absolute_url(self):
     return reverse('players', args=[self.id])

basketball_site/players/views.py
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from .models import Player
from django.urls import reverse_lazy
# Create your views here.
class PlayerListView(ListView):
  model = Player
  template_name = 'home.html'

class PlayerDetailView(DetailView):
  model = Player
  template_name = 'players.html'  

class PlayerCreateView(CreateView):
  model = Player
  template_name = 'create_players.html'
  fields = ['player_name', 'height', 'weight', 'position', 'author']

class PlayerDeleteView(DeleteView):
  model = Player
  template_name = 'delete_players.html'
  success_url = reverse_lazy('home')

class PlayerUpdateView(UpdateView):
  model = Player
  template_name = 'edit_players.html'
  fields = ['player_name', 'height', 'weight', 'position']

basketball_site/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Player Profiles</title>
</head>

<body>
  <header>
    <div>
      <a href="{% url 'home' %}">Player Profiles</a>
    </div>
    <div>
      <a href="{% url 'player_new' %}">New Player</a>
    </div>
  </header>
  <div>
    {% block content %}
    {% endblock content %}
  </div>
</body>

</html>

basketball_site/templates/create_players.html
{% extends 'base.html' %}

{% block content %}
<h1>Add New Player</h1>
<form action="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="Save">
</form>
{% endblock content %}

basketball_site/templates/delete_players.html
{% extends 'base.html' %}

{% block content %}
<h1>Remove Player</h1>
<form action="" method="post">
  {% csrf_token %}
  <p>Sure you want to remove "{{player.player_name}}" ?</p>
  <input type="submit" value="Confirm">
</form>
{% endblock content %}

basketball_site/templates/edit_players.html
{% extends 'base.html' %}

{% block content %}
<h1>Edit Player</h1>
<form action="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="Save Changes">
</form>
{% endblock content %}

basketball_site/templates/home.html
{% extends 'base.html' %}

{% block content %}
  {% for player in object_list %}
  <div>
    <h2><a href="{% url 'players' player.pk %}">{{player.player_name}}</a></h2>
  </div>
  {% endfor %}


{% endblock content %}  

basketball_site/templates/players.html
{% extends 'base.html' %}

{% block content %}
<div>
  <h2>{{player.player_name}}</h2>
  <p>Position: {{player.get_position_display}}</p>
  <p>Height: {{player.height}}</p>
  <p>Weight: {{player.weight}}</p>
  <p><a href="{% url 'player_edit' player.id %}">Edit Player</a></p>
  <p><a href="{% url 'player_delete' player.id %}">Remove Player</a></p>

</div>
{% endblock content %} 